#!/usr/bin/python
"""
run this occasionally. 

first get a new xml file:
wget http://pems.dot.ca.gov/vds_config.xml

then run this program to replace the 'vds' table in monet

"""

from freeway.db import getDb
from freeway.ingest import detector

db = getDb()

newData = detector.parseVdsConfig("vds_config.xml")


rows = []

for id, vds in newData.items():
    vds['id'] = id
    rows.append(vds)

db.replaceVds(rows)
