#!bin/python
import sys
sys.path.insert(0, ".")
from twisted.internet import reactor
import freeway.ingest.ingestd
from freeway.db import getDb

db = getDb()

loop = freeway.ingest.ingestd.UpdateLoop(db, mock=False)
reactor.run()
